#!/usr/bin/env bash
set -Eeuo pipefail

cd "$(dirname "$0")"
ROOT_DIR="$(pwd)"
RUN_DIR="${ROOT_DIR}/.run/backendai"
LOG_DIR="${ROOT_DIR}/logs/backendai"
ENV_FILE="${ROOT_DIR}/.env"
ENV_TEMPLATE="${ROOT_DIR}/.env.backendai.example"

export UV_PROJECT_ENVIRONMENT="${UV_PROJECT_ENVIRONMENT:-.venv-app}"
unset VIRTUAL_ENV || true

if [[ "${UV_PROJECT_ENVIRONMENT}" = /* ]]; then
  VENV_DIR="${UV_PROJECT_ENVIRONMENT}"
else
  VENV_DIR="${ROOT_DIR}/${UV_PROJECT_ENVIRONMENT}"
fi

mkdir -p "${RUN_DIR}" "${LOG_DIR}"

fail() {
  echo "ERROR: $*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "required command not found: $1"
}

require_command uv
require_command npm
require_command node
require_command curl
require_command python3

if [[ ! -f "${ENV_FILE}" ]]; then
  cp "${ENV_TEMPLATE}" "${ENV_FILE}"
  python3 - "${ENV_FILE}" <<'PY'
from pathlib import Path
import secrets
import sys

path = Path(sys.argv[1])
text = path.read_text()
text = text.replace(
    "JWT_SECRET=CHANGE_ME_AUTOGENERATED_BY_RUN_BACKENDAI",
    f"JWT_SECRET={secrets.token_hex(32)}",
)
path.write_text(text)
PY
  echo "Created .env from .env.backendai.example with a random JWT secret."
  echo "Edit DATABASE_URL/VECTOR_DB_URL, then run ./run_backendai.sh again."
  exit 2
fi

set -a
# shellcheck disable=SC1090
source "${ENV_FILE}"
set +a

DATABASE_URL="${DATABASE_URL:-}"
VECTOR_DB_URL="${VECTOR_DB_URL:-}"
JWT_SECRET_VALUE="${JWT_SECRET:-}"
BACKEND_PORT="${BACKENDAI_BACKEND_PORT:-8000}"
FRONTEND_PORT="${BACKENDAI_FRONTEND_PORT:-3000}"
FRONTEND_MODE="${BACKENDAI_FRONTEND_MODE:-dev}"

[[ -n "${DATABASE_URL}" ]] || fail "DATABASE_URL is empty"
if [[ "${DATABASE_URL}" == *"CHANGE_ME"* || "${DATABASE_URL}" == *"DB_HOST"* ]]; then
  fail "configure DATABASE_URL in .env before starting Backend.AI"
fi
if [[ -n "${VECTOR_DB_URL}" && ( "${VECTOR_DB_URL}" == *"CHANGE_ME"* || "${VECTOR_DB_URL}" == *"DB_HOST"* ) ]]; then
  fail "configure VECTOR_DB_URL in .env before starting Backend.AI"
fi
if [[ -z "${JWT_SECRET_VALUE}" || "${JWT_SECRET_VALUE}" == *"CHANGE_ME"* || ${#JWT_SECRET_VALUE} -lt 32 ]]; then
  fail "JWT_SECRET must be a unique secret of at least 32 characters"
fi
if [[ "${NEXT_PUBLIC_API_BASE_URL:-}" == *"BACKENDAI_BACKEND_APP_URL"* ]]; then
  echo "WARN: NEXT_PUBLIC_API_BASE_URL still has the Backend.AI App Proxy placeholder."
  echo "      Local health checks will work, but browser API calls will not until you replace it."
fi
if [[ "${BACKEND_CORS_ORIGINS:-}" == *"BACKENDAI_FRONTEND_APP_URL"* ]]; then
  echo "WARN: BACKEND_CORS_ORIGINS still has the Backend.AI App Proxy placeholder."
fi

case "${FRONTEND_MODE}" in
  dev|production) ;;
  *) fail "BACKENDAI_FRONTEND_MODE must be dev or production" ;;
esac

if [[ -f "${ROOT_DIR}/stop_backendai.sh" ]]; then
  bash "${ROOT_DIR}/stop_backendai.sh" --quiet || true
fi

port_in_use() {
  python3 - "$1" <<'PY'
import socket
import sys

port = int(sys.argv[1])
with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
    sock.settimeout(0.2)
    raise SystemExit(0 if sock.connect_ex(("127.0.0.1", port)) == 0 else 1)
PY
}

if port_in_use "${BACKEND_PORT}"; then
  fail "port ${BACKEND_PORT} is already in use by an unmanaged process"
fi
if port_in_use "${FRONTEND_PORT}"; then
  fail "port ${FRONTEND_PORT} is already in use by an unmanaged process"
fi

if [[ "${TEXT_LLM_BASE_URL:-}" != http://127.0.0.1:* && "${TEXT_LLM_BASE_URL:-}" != http://localhost:* ]]; then
  echo "WARN: TEXT_LLM_BASE_URL is not loopback; expected same-session Model Server for Backend.AI."
fi


echo "==> Syncing Python workspace (CPU-only voice dependencies)"
uv sync --locked --all-packages --extra voice

PYTHON_BIN="${VENV_DIR}/bin/python"
UVICORN_BIN="${VENV_DIR}/bin/uvicorn"
ALEMBIC_BIN="${VENV_DIR}/bin/alembic"
[[ -x "${PYTHON_BIN}" ]] || fail "Python environment was not created at ${VENV_DIR}"
[[ -x "${UVICORN_BIN}" ]] || fail "uvicorn is missing from ${VENV_DIR}"
[[ -x "${ALEMBIC_BIN}" ]] || fail "alembic is missing from ${VENV_DIR}"

if [[ -f package-lock.json ]]; then
  echo "==> Installing frontend dependencies from package-lock.json"
  npm ci
else
  echo "==> Installing frontend dependencies"
  npm install
fi

NEXT_BIN="${ROOT_DIR}/node_modules/.bin/next"
[[ -x "${NEXT_BIN}" ]] || fail "Next.js binary was not installed"


echo "==> Checking PostgreSQL connectivity"
"${PYTHON_BIN}" - <<'PY'
from sqlalchemy import create_engine, text
from app.core.config import get_settings

settings = get_settings()
engine = create_engine(settings.database_url, pool_pre_ping=True)
try:
    with engine.connect() as connection:
        connection.execute(text("SELECT 1"))
finally:
    engine.dispose()
print("PostgreSQL: OK")
PY


echo "==> Checking local Model Server"
"${PYTHON_BIN}" - <<'PY'
import json
from app.core.config import get_settings
from app.services.model_server import check_model_server_health

health = check_model_server_health(get_settings())
print(json.dumps(health.as_dict(), ensure_ascii=False))
if not health.all_available:
    raise SystemExit("Model Server is not fully ready; start SKKU_AI_model_server first")
print("Model Server: OK")
PY


echo "==> Applying database migrations"
"${ALEMBIC_BIN}" -c apps/backend/alembic.ini upgrade head

if [[ "${BACKENDAI_SEED:-true}" == "true" ]]; then
  echo "==> Seeding development accounts/data"
  "${PYTHON_BIN}" -m app.db.seed
else
  echo "==> Skipping seed (BACKENDAI_SEED=${BACKENDAI_SEED:-false})"
fi

if [[ "${FRONTEND_MODE}" == "production" ]]; then
  echo "==> Building Next.js frontend"
  npm run build:frontend
fi

BACKEND_LOG="${LOG_DIR}/backend.log"
FRONTEND_LOG="${LOG_DIR}/frontend.log"
BACKEND_PID_FILE="${RUN_DIR}/backend.pid"
FRONTEND_PID_FILE="${RUN_DIR}/frontend.pid"

cleanup_started_processes() {
  bash "${ROOT_DIR}/stop_backendai.sh" --quiet || true
}

start_backend() {
  echo "==> Starting FastAPI on 0.0.0.0:${BACKEND_PORT}"
  nohup "${UVICORN_BIN}" app.main:app \
    --app-dir apps/backend \
    --host 0.0.0.0 \
    --port "${BACKEND_PORT}" \
    >"${BACKEND_LOG}" 2>&1 &
  echo $! >"${BACKEND_PID_FILE}"
}

start_frontend() {
  echo "==> Starting Next.js (${FRONTEND_MODE}) on 0.0.0.0:${FRONTEND_PORT}"
  if [[ "${FRONTEND_MODE}" == "production" ]]; then
    nohup "${NEXT_BIN}" start "${ROOT_DIR}/apps/frontend" \
      --hostname 0.0.0.0 \
      --port "${FRONTEND_PORT}" \
      >"${FRONTEND_LOG}" 2>&1 &
  else
    nohup "${NEXT_BIN}" dev "${ROOT_DIR}/apps/frontend" \
      --hostname 0.0.0.0 \
      --port "${FRONTEND_PORT}" \
      >"${FRONTEND_LOG}" 2>&1 &
  fi
  echo $! >"${FRONTEND_PID_FILE}"
}

wait_http() {
  local name="$1"
  local url="$2"
  local pid_file="$3"
  local log_file="$4"
  local timeout_seconds="$5"
  local waited=0
  local pid
  pid="$(cat "${pid_file}")"

  echo "==> Waiting for ${name}: ${url}"
  while (( waited < timeout_seconds )); do
    if ! kill -0 "${pid}" 2>/dev/null; then
      echo "${name} exited before becoming ready. Last log lines:" >&2
      tail -n 120 "${log_file}" >&2 || true
      return 1
    fi
    if curl -fsS --max-time 3 "${url}" >/dev/null 2>&1; then
      echo "    ${name}: READY (pid ${pid})"
      return 0
    fi
    sleep 2
    waited=$((waited + 2))
  done

  echo "${name} did not become ready within ${timeout_seconds}s. Last log lines:" >&2
  tail -n 120 "${log_file}" >&2 || true
  return 1
}

start_backend
if ! wait_http "backend" "http://127.0.0.1:${BACKEND_PORT}/api/health" "${BACKEND_PID_FILE}" "${BACKEND_LOG}" 120; then
  cleanup_started_processes
  exit 1
fi

start_frontend
if ! wait_http "frontend" "http://127.0.0.1:${FRONTEND_PORT}/" "${FRONTEND_PID_FILE}" "${FRONTEND_LOG}" 180; then
  cleanup_started_processes
  exit 1
fi

MODEL_HEALTH="$(curl -fsS --max-time 5 "http://127.0.0.1:${BACKEND_PORT}/api/health/model-server")"
if ! python3 - "${MODEL_HEALTH}" <<'PY'
import json
import sys

payload = json.loads(sys.argv[1])
raise SystemExit(0 if payload.get("status") == "ok" else 1)
PY
then
  echo "Backend started, but its Model Server health is not OK:" >&2
  echo "${MODEL_HEALTH}" >&2
  cleanup_started_processes
  exit 1
fi

cat <<EOF

Backend.AI application is READY.
Frontend : http://127.0.0.1:${FRONTEND_PORT}
Backend  : http://127.0.0.1:${BACKEND_PORT}
API docs : http://127.0.0.1:${BACKEND_PORT}/docs
Model API: http://127.0.0.1:${BACKEND_PORT}/api/health/model-server
Logs     : ${LOG_DIR}

Expose preopen ports ${FRONTEND_PORT} and ${BACKEND_PORT} in Backend.AI.
Then set:
  NEXT_PUBLIC_API_BASE_URL=<Backend.AI URL for port ${BACKEND_PORT}>
  BACKEND_CORS_ORIGINS=<Backend.AI URL for port ${FRONTEND_PORT}>
and restart this script if those values were placeholders.
EOF
