"""COURSE AGENT brain, course-scoped for the SKKU Course Agent backend.

Ported from the standalone ``kingo-voice-agent`` repository. Behaviour is
unchanged apart from four integration points:

* answers are generated by this project's ``LLMService`` (Claude, or the
  deterministic mock) instead of the upstream xAI chat model, so the whole
  product has one answer-generation boundary and one configuration surface.
  Only the realtime speech-to-speech leg still runs on xAI Grok, because
  Claude has no realtime voice API.
* ``search_course_materials`` retrieves through the existing course-scoped
  ``RagService`` (pgvector) instead of re-indexing a private PDF folder, so
  sources keep the ``filename p.page`` shape professors already see.
* the trusted-web allowlist and the conversation history are per course and per
  user instead of process-global.
* weak-concept memory is keyed by the authenticated user id.
"""

from __future__ import annotations

import asyncio
import json
import logging
import re
import time
from contextlib import contextmanager
from dataclasses import dataclass, field
from typing import Awaitable, Callable, Literal, Optional

from pydantic import BaseModel, Field

from app.core.config import get_settings
from app.services.llm_service import LLMError, LLMService
from app.services.voice.moss_memory import MossMemoryStore
from app.services.voice.storage import voice_storage_dir
from app.services.voice.trusted_sites import get_trusted_domains

log = logging.getLogger("voice.brain")

PDF_MAX_RESULTS = 3
MAX_HISTORY_MESSAGES = 12
MAX_TOOL_ROUNDS = 6


class VoiceNotConfiguredError(RuntimeError):
    """Raised when the realtime voice leg is used without an xAI API key."""


def require_api_key() -> str:
    """Return the xAI key used by the realtime speech-to-speech transport."""
    settings = get_settings()
    key = (settings.xai_api_key or "").strip()
    if not key:
        raise VoiceNotConfiguredError(
            "XAI_API_KEY is not set. Copy .env.example to .env and fill it in; "
            "model names and voices live at https://docs.x.ai. "
            "Text answers do not need it."
        )
    return key


class StageTimer:
    def __init__(self) -> None:
        self.timings_ms: dict[str, int] = {}

    @contextmanager
    def stage(self, name: str):
        t0 = time.perf_counter()
        try:
            yield
        finally:
            ms = round((time.perf_counter() - t0) * 1000)
            self.timings_ms[name] = ms
            log.info("stage %-5s %5d ms", name, ms)

    def record(self, name: str, started_at: float) -> None:
        ms = round((time.perf_counter() - started_at) * 1000)
        self.timings_ms[name] = ms
        log.info("stage %-5s %5d ms", name, ms)


class TextQuestion(BaseModel):
    text: str = Field(min_length=1, max_length=4000)
    mode: Literal["explain", "socratic"] = "socratic"


class WeakConceptCapture(BaseModel):
    course: str
    concept: str
    original_question: str
    difficulty_note: str


class PlotPoint(BaseModel):
    x: float = Field(ge=-1e12, le=1e12)
    y: float = Field(ge=-1e12, le=1e12)


class Visualization(BaseModel):
    title: str = Field(min_length=1, max_length=120)
    kind: Literal["formula", "flow", "plot"]
    caption: str = Field(min_length=1, max_length=300)
    latex: str = Field(max_length=1000)
    labels: list[str] = Field(max_length=8)
    points: list[PlotPoint] = Field(max_length=40)
    x_label: str = Field(max_length=40)
    y_label: str = Field(max_length=40)


@dataclass
class VoiceContext:
    """Everything one learner's session with one course agent needs."""

    course_id: str
    course_name: str
    user_id: str
    memory: MossMemoryStore
    history: list[dict] = field(default_factory=list)
    # Structured citations of the last course-material search, reused when the
    # turn is written to the shared chat log.
    last_material_sources: list[dict] = field(default_factory=list)
    # Chat session the turns of this conversation are logged under.
    chat_session_id: Optional[str] = None

    def append_history(self, message: dict) -> None:
        self.history.append(message)
        if len(self.history) > MAX_HISTORY_MESSAGES:
            del self.history[:-MAX_HISTORY_MESSAGES]

    def reset(self) -> None:
        self.history.clear()
        self.last_material_sources.clear()
        self.chat_session_id = None
        log.info("voice conversation reset: course=%s user=%s", self.course_id, self.user_id)


SYSTEM_PROMPT = """
# Role and objective
You are COURSE AGENT, a Socratic voice teaching assistant for one
Sungkyunkwan University student.

# Language and speaking style
Speak in Korean unless asked otherwise. Use natural spoken Korean in the
polite 해요 style, as if talking with the student face to face. Prefer endings
such as 해요, 예요, 볼까요, and 해볼게요. Avoid written declarative endings such
as 한다, 이다, and 하였다, and avoid textbook or report-like prose unless you are
quoting a source.

# Tool workflow
At the start of every student turn, call recall_weak_concepts and
search_course_materials together.

# Evidence and sources
Base factual claims only on tool results. For PDF evidence, state filename and
page, but paraphrase any equation instead of quoting or reading it. Put the
exact equation in show_visualization. If PDF evidence is missing or
insufficient, call search_trusted_web.
Return source URLs through the separate sources field; do not repeat raw URLs
in the conversational answer.

# Learning memory
Use recalled weaknesses to personalize hints and check prerequisites. Call
save_weak_concept only for explicit confusion, an incorrect answer, or an
incomplete explanation; ordinary questions are not weaknesses. When the
student answers a review prompt containing a memory id, call
review_weak_concept with your correctness judgment.

# Visual references
Never put raw equations, symbolic notation, diagrams, or coordinate data in
the conversational answer and never read them symbol by symbol. When the
answer would otherwise contain a formula, process diagram, or graph, you MUST
call show_visualization first and put the exact visual data only in that tool.
Treat any mathematical expression—including a single equation, variable
relationship, Greek letter, fraction, exponent, subscript, or LaTeX—as a
formula. When unsure whether visual support is useful, prefer calling
show_visualization. Do not send the final conversational answer until that tool
has succeeded. In the spoken answer, explain only what the visual means; never
repeat its LaTeX, symbols, equation, or coordinates, even when quoting a PDF.
Then explain it naturally with a reference such as '제가 보여드린 그림처럼'.

# Academic integrity
Never hand over a complete assignment answer, report, or exam solution. Turn
those requests into hints, concepts, and step-by-step learning guidance.

# Response format
Use one to three short conversational sentences with no markdown lists. Never
read raw JSON aloud.
""".strip()

MODE_PROMPTS = {
    "explain": (
        "Explanation mode: explain the concept directly in plain Korean, give "
        "one concrete example, then ask one short understanding-check question."
    ),
    "socratic": (
        "Socratic mode: do not reveal the final answer first. Ask one focused "
        "question or give one progressive hint that makes the student reason."
    ),
}

TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "recall_weak_concepts",
            "description": (
                "Recall semantically relevant weak concepts for this student. "
                "Call on every student turn before answering."
            ),
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                    "topic": {
                        "type": "string",
                        "description": "Current question or concept used for memory retrieval.",
                    },
                },
                "required": ["topic"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "search_course_materials",
            "description": (
                "Search the professor-uploaded materials of this course for grounded "
                "evidence. Call on every student turn before answering."
            ),
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Focused terms from the student question.",
                    },
                },
                "required": ["query"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "search_trusted_web",
            "description": (
                "Search trusted academic or SKKU domains only after course "
                "material search is missing or insufficient."
            ),
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Focused external search query.",
                    },
                    "reason": {
                        "type": "string",
                        "description": "Specific gap in course material evidence.",
                    },
                },
                "required": ["query", "reason"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "save_weak_concept",
            "description": (
                "Save a weak concept only after confusion, an incorrect answer, "
                "or an incomplete explanation. Do not save ordinary questions."
            ),
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                    "course": {
                        "type": "string",
                        "description": "Course containing the weak concept.",
                    },
                    "concept": {
                        "type": "string",
                        "description": "Concise weak-concept label.",
                    },
                    "original_question": {
                        "type": "string",
                        "description": "Student question exposing the weakness.",
                    },
                    "difficulty_note": {
                        "type": "string",
                        "description": "Observed misunderstanding or missing prerequisite.",
                    },
                },
                "required": [
                    "course",
                    "concept",
                    "original_question",
                    "difficulty_note",
                ],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "review_weak_concept",
            "description": (
                "Update spaced-repetition state when the student answers a "
                "review question containing a memory id."
            ),
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                    "memory_id": {
                        "type": "string",
                        "description": "Weak-concept memory id from the review prompt.",
                    },
                    "correct": {
                        "type": "boolean",
                        "description": "Whether the student explanation is correct.",
                    },
                },
                "required": ["memory_id", "correct"],
                "additionalProperties": False,
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "show_visualization",
            "description": (
                "Show a safe visual reference instead of putting formulas, diagrams, "
                "or graph coordinates in the spoken answer. Prefer calling this even "
                "for one equation or variable relationship, and whenever visual support "
                "might help. Use formula for LaTeX, "
                "flow for ordered labeled steps, or plot for numeric x/y points."
            ),
            "strict": True,
            "parameters": {
                "type": "object",
                "properties": {
                    "title": {"type": "string", "description": "Short Korean title."},
                    "kind": {"type": "string", "enum": ["formula", "flow", "plot"]},
                    "caption": {
                        "type": "string",
                        "description": "One concise Korean takeaway.",
                    },
                    "latex": {
                        "type": "string",
                        "description": (
                            "Raw LaTeX without dollar delimiters; empty unless kind is formula."
                        ),
                    },
                    "labels": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Ordered node labels; empty unless kind is flow.",
                    },
                    "points": {
                        "type": "array",
                        "description": "Numeric points; empty unless kind is plot.",
                        "items": {
                            "type": "object",
                            "properties": {
                                "x": {"type": "number"},
                                "y": {"type": "number"},
                            },
                            "required": ["x", "y"],
                            "additionalProperties": False,
                        },
                    },
                    "x_label": {
                        "type": "string",
                        "description": "Plot x-axis label, otherwise empty.",
                    },
                    "y_label": {
                        "type": "string",
                        "description": "Plot y-axis label, otherwise empty.",
                    },
                },
                "required": [
                    "title",
                    "kind",
                    "caption",
                    "latex",
                    "labels",
                    "points",
                    "x_label",
                    "y_label",
                ],
                "additionalProperties": False,
            },
        },
    },
]


def anthropic_tools() -> list[dict]:
    """Convert the shared tool schemas to Anthropic's tool format.

    ``TOOLS`` stays in OpenAI/realtime shape because the Grok speech-to-speech
    transport consumes it directly; Claude needs ``input_schema`` instead.
    """
    return [
        {
            "name": tool["function"]["name"],
            "description": tool["function"]["description"],
            "input_schema": tool["function"]["parameters"],
        }
        for tool in TOOLS
    ]


# --------------------------------------------------------------------------
# Tool implementations.
# --------------------------------------------------------------------------


def _json(data: dict) -> str:
    return json.dumps(data, ensure_ascii=False)


def _tool_log_value(value: object, limit: int = 600) -> str:
    """Return compact, bounded JSON for tool debugging logs."""
    if isinstance(value, str):
        try:
            value = json.loads(value)
        except json.JSONDecodeError:
            pass
    text = json.dumps(value, ensure_ascii=False, default=str, separators=(",", ":"))
    return text if len(text) <= limit else f"{text[:limit]}…"


def show_visualization(**args) -> str:
    """Validate one formula, flow diagram, or numeric plot for the chat UI.

    Args:
        **args: Structured visualization fields from the model tool call.

    Returns:
        JSON string containing only validated, render-safe data.
    """
    visualization = Visualization(**args)
    if visualization.kind == "formula" and not visualization.latex.strip():
        raise ValueError("formula visualization requires latex")
    if visualization.kind == "flow" and len(visualization.labels) < 2:
        raise ValueError("flow visualization requires at least two labels")
    if visualization.kind == "plot" and len(visualization.points) < 2:
        raise ValueError("plot visualization requires at least two points")
    return _json(visualization.model_dump())


def _terms(text: str) -> set[str]:
    return {
        token.casefold()
        for token in re.findall(r"[0-9A-Za-z가-힣_]{2,}", text)
        if token.casefold() not in {"대해서", "설명", "질문", "무엇", "어떻게"}
    }


def search_course_materials(course_id: str, query: str) -> tuple[str, list[dict]]:
    """Search the course knowledge base through the shared RAG service.

    Args:
        course_id: Course whose processed materials may be searched.
        query: Focused terms from the student question.

    Returns:
        Tuple of the JSON tool result and the structured citations for logging.
    """
    # Imported here so the voice package stays importable without a database.
    from app.core.config import get_settings
    from app.db.session import SessionLocal
    from app.services.rag_service import RagService

    query = (query or "").strip()
    if not _terms(query):
        return _json({"error": "a focused course-material search query is required"}), []

    with SessionLocal() as session:
        outcome = RagService(session, get_settings()).retrieve(course_id, query, PDF_MAX_RESULTS)

    citations = [
        {
            "material_id": result.material_id,
            "document_name": result.document_name,
            "page_number": result.page_number,
            "chunk_index": result.chunk_index,
            "score": round(result.score, 4),
        }
        for result in outcome.results
    ]
    results = [
        {
            "source": _source_label(result.document_name, result.page_number),
            "excerpt": result.chunk_text.strip()[:1000],
        }
        for result in outcome.results
    ]
    payload = {
        "found": bool(results),
        "query": query,
        "results": results,
        "instruction": (
            "Use the document name and page in the answer."
            if results
            else "No course-material evidence found; trusted web search is now allowed."
        ),
    }
    if not results and outcome.summary.reason:
        payload["reason"] = outcome.summary.reason
    return _json(payload), citations


def _source_label(document_name: str, page_number: Optional[int]) -> str:
    return f"{document_name} p.{page_number}" if page_number else document_name


WEB_SEARCH_SYSTEM_PROMPT = (
    "Answer in Korean using only the web-search evidence. "
    "Keep source URLs in the tool result, not in the prose answer. "
    "If evidence is insufficient, say so."
)


async def search_trusted_web(
    course_id: str,
    query: str,
    pdf_evidence_insufficient: bool = False,
    reason: str = "",
) -> str:
    """Search the course allowlist through Claude and retain citation audit data.

    Args:
        course_id: Course whose professor-managed allowlist applies.
        query: Focused external search query.
        pdf_evidence_insufficient: Whether course material evidence is insufficient.
        reason: Evidence gap permitting web fallback.

    Returns:
        JSON string with cited answer and trusted source URLs.
    """
    query = (query or "").strip()
    reason = (reason or "").strip()
    if not query:
        return _json({"error": "web search query is required"})
    if not reason:
        return _json({"error": "course-material fallback reason is required"})

    try:
        found = await LLMService(get_settings()).search_web(
            query=query,
            system=WEB_SEARCH_SYSTEM_PROMPT,
            allowed_domains=get_trusted_domains(course_id),
        )
    except LLMError as exc:
        return _json({"error": str(exc), "query": query})

    answer, sources = found.answer, found.sources
    if not answer or not sources:
        return _json(
            {
                "error": "trusted web search returned no citable sources",
                "query": query,
            }
        )

    record = {
        "course_id": course_id,
        "query": query,
        "answer": answer,
        "sources": sources,
        "pdf_evidence_insufficient": pdf_evidence_insufficient,
        "fallback_reason": reason,
        "searched_at": time.time(),
    }
    log_path = voice_storage_dir() / "web-search.jsonl"
    with log_path.open("a", encoding="utf-8") as file:
        file.write(_json(record) + "\n")
    return _json(
        {
            "found": True,
            "answer": answer,
            "sources": sources,
            "instruction": "The UI displays source URLs separately; do not repeat them in the answer.",
        }
    )


async def run_tool(context: VoiceContext, name: str, args: dict, timer: StageTimer) -> str:
    """Dispatch one validated function tool call.

    Args:
        context: Course-scoped session state.
        name: Tool name emitted by Grok.
        args: Parsed JSON arguments matching the tool schema.
        timer: Collector receiving tool latency.

    Returns:
        JSON string containing tool output or a recoverable error.
    """
    started_at = time.perf_counter()
    stage = {
        "recall_weak_concepts": "recall",
        "search_course_materials": "material",
        "search_trusted_web": "web",
        "save_weak_concept": "save",
        "review_weak_concept": "review",
        "show_visualization": "visual",
    }.get(name, "tool")
    log.info("tool call name=%s args=%s", name, _tool_log_value(args))
    try:
        if not isinstance(args, dict):
            raise TypeError("tool arguments must be an object")
        if name == "recall_weak_concepts":
            result = _json(await context.memory.recall(**args))
        elif name == "search_course_materials":
            result, citations = await asyncio.to_thread(
                search_course_materials, context.course_id, **args
            )
            if citations:
                context.last_material_sources = citations
        elif name == "search_trusted_web":
            result = await search_trusted_web(
                context.course_id,
                pdf_evidence_insufficient=True,
                **args,
            )
        elif name == "save_weak_concept":
            result = _json(await context.memory.save(**args))
        elif name == "review_weak_concept":
            result = _json(await context.memory.review(**args))
        elif name == "show_visualization":
            result = show_visualization(**args)
        else:
            result = _json({"error": f"unknown tool: {name}"})
    except (TypeError, ValueError) as exc:
        result = _json({"error": f"invalid {name} arguments: {exc}"})
    except Exception as exc:
        log.exception("tool %s failed", name)
        result = _json({"error": str(exc)})
    finally:
        timer.record(stage, started_at)
    payload = json.loads(result)
    status = "error" if isinstance(payload, dict) and "error" in payload else "ok"
    elapsed_ms = round((time.perf_counter() - started_at) * 1000)
    log.info(
        "tool result name=%s status=%s elapsed_ms=%d result=%s",
        name,
        status,
        elapsed_ms,
        _tool_log_value(payload),
    )
    return result


# --------------------------------------------------------------------------
# Function-tool response pipeline.
# --------------------------------------------------------------------------

CONFUSION_MARKERS = (
    "모르겠", "모르겠어", "잘 모르", "어려워", "어렵", "헷갈",
    "이해가 안", "이해 안", "이해되지", "감이 안", "막혀", "틀린 것 같",
    "don't know", "do not know", "confused", "difficult", "hard to understand",
)


def _explicit_confusion(transcript: str) -> bool:
    normalized = transcript.casefold()
    return any(marker in normalized for marker in CONFUSION_MARKERS)


def _fallback_weak_concept(course_name: str, transcript: str) -> WeakConceptCapture:
    concise_question = re.sub(r"\s+", " ", transcript).strip()
    return WeakConceptCapture(
        course=course_name or "미지정 과목",
        concept=concise_question[:160],
        original_question=concise_question,
        difficulty_note="학생이 명시적으로 이해 부족, 혼란 또는 어려움을 표현함",
    )


REQUIRED_CONTEXT_TOOLS = ("recall_weak_concepts", "search_course_materials")


def _conversation(history: list[dict]) -> list[dict]:
    """Return the history trimmed to something Claude accepts.

    A conversation must start with a user message; a pending review prompt can
    leave an assistant message first, so drop any leading assistant turns.
    """
    start = 0
    while start < len(history) and history[start].get("role") != "user":
        start += 1
    return history[start:]


async def think(
    context: VoiceContext,
    transcript: str,
    timer: StageTimer,
    mode: str = "socratic",
    on_token: Callable[[str], Awaitable[None]] | None = None,
) -> tuple[str, list[str], list[str], list[dict]]:
    """Generate one grounded Socratic response through Claude's tool use.

    Args:
        context: Course-scoped session state.
        transcript: Student utterance transcribed to text.
        timer: Collector for tool and model latency.
        mode: Learner-selected explanation or Socratic mode.
        on_token: Optional callback receiving streamed answer tokens.

    Returns:
        Reply text, tool names, trusted source URLs, and visual references.
    """
    context.append_history({"role": "user", "content": transcript})
    context.last_material_sources = []
    llm = LLMService(get_settings())
    tool_messages: list[dict] = []
    tools_used: list[str] = []
    external_sources: list[str] = []
    visualizations: list[dict] = []
    system = "\n\n".join(
        (
            SYSTEM_PROMPT,
            f"# Course\n이 대화는 성균관대학교 '{context.course_name}' 과목의 AI 조교 "
            "세션입니다. 강의자료 검색은 이 과목으로만 한정됩니다.",
            MODE_PROMPTS.get(mode, MODE_PROMPTS["socratic"]),
        )
    )
    tools = anthropic_tools()

    for _ in range(MAX_TOOL_ROUNDS):
        missing_context = [name for name in REQUIRED_CONTEXT_TOOLS if name not in tools_used]
        started_at = time.perf_counter()
        turn = await llm.stream_tool_turn(
            system=system,
            messages=[*_conversation(context.history), *tool_messages],
            tools=tools,
            force_tools=missing_context,
            on_token=on_token,
        )
        elapsed_ms = round((time.perf_counter() - started_at) * 1000)
        timer.timings_ms["llm"] = timer.timings_ms.get("llm", 0) + elapsed_ms
        log.info("stage llm   %5d ms (%s)", elapsed_ms, turn.model_name)

        if not turn.tool_calls:
            reply_text = turn.text.strip() or "답변을 생성하지 못했어요. 다시 질문해 주세요."
            if external_sources:
                reply_text = for_speech(reply_text)

            if _explicit_confusion(transcript) and "save_weak_concept" not in tools_used:
                memory = _fallback_weak_concept(context.course_name, transcript)
                await run_tool(context, "save_weak_concept", memory.model_dump(), timer)
                tools_used.append("save_weak_concept")

            context.append_history({"role": "assistant", "content": reply_text})
            return reply_text, tools_used, external_sources[:3], visualizations

        assistant_blocks: list[dict] = []
        if turn.text.strip():
            assistant_blocks.append({"type": "text", "text": turn.text})
        assistant_blocks.extend(
            {"type": "tool_use", "id": call.id, "name": call.name, "input": call.arguments}
            for call in turn.tool_calls
        )
        tool_messages.append({"role": "assistant", "content": assistant_blocks})

        results = await asyncio.gather(
            *(run_tool(context, call.name, call.arguments, timer) for call in turn.tool_calls)
        )
        result_blocks: list[dict] = []
        for call, result in zip(turn.tool_calls, results):
            if call.name not in tools_used:
                tools_used.append(call.name)
            if call.name == "search_trusted_web":
                external_sources = json.loads(result).get("sources", [])
            elif call.name == "show_visualization":
                visual = json.loads(result)
                if "error" not in visual:
                    visualizations.append(visual)
            result_blocks.append(
                {"type": "tool_result", "tool_use_id": call.id, "content": result}
            )
        tool_messages.append({"role": "user", "content": result_blocks})

    raise RuntimeError("the assistant exceeded the tool-call round limit")


# --------------------------------------------------------------------------
# Speech and lifecycle helpers.
# --------------------------------------------------------------------------


def for_speech(text: str) -> str:
    """Remove URLs from speech while keeping them in screen text."""
    text = re.sub(
        r"\s*외부 출처\s*:?\s*(?:https?://\S+\s*,?\s*)+$", "", text,
        flags=re.IGNORECASE,
    )
    return re.sub(r"https?://\S+", "", text).strip()


# Kept under the original private name so ported tests keep passing.
_for_speech = for_speech


async def next_review_prompt(context: VoiceContext) -> dict:
    """Return the next due weak concept for this learner, if any."""
    memory = await context.memory.next_review()
    if memory is None:
        return {"due": False}
    question = f"{memory['concept']}을 자신의 말로 설명해 볼까요?"
    context.append_history({
        "role": "assistant",
        "content": f"복습 질문 (memory_id={memory['id']}): {question}",
    })
    return {
        "due": True,
        "memory_id": memory["id"],
        "concept": memory["concept"],
        "question": question,
    }
